### ISSUE TITLE
GNPS MolNetEnhancer Theory Tutorial Slides

### ISSUE THREAD

**Issue by amcaraballor** [CCMS-UCSD/GNPS_TrainingTutorialModules#10]
Hey @mwang87, additional [MolNetEnhancer Theory Module](https://www.dropbox.com/s/r3vaa9radbjczz4/MolNetEnhancer_theory.pptx?dl=0)

**Comment by mwang87** [comment]
Can you send a PR for the file in the right location. I'm not sure how this relates to the existing powerpoint that is there for molnetenhancer, does it replace it?

**Comment by amcaraballor** [comment]
This one contains the figures to explain the concept (theory). We can keep both, as the existing one is a brief example with the job link.
