### ISSUE TITLE
GNPS Finalize FBMN Tutorial Slides - MS2LDA 

### ISSUE THREAD

**Issue by mwang87** [CCMS-UCSD/GNPS_TrainingTutorialModules#7]

**Comment by justinjjvanderhooft** [comment]
You can assign me to this one Ming! (it seems I cannot do it myself)

**Comment by mwang87** [comment]
@justinjjvanderhooft Any updates on this tutorial module?

**Comment by justinjjvanderhooft** [comment]
Thanks for the heads up @mingxunwang - will dig up the slides from Prague and polish where needed. Will share a link here. I might prepare new slides for the December workshop here in Wageningen - will share those slides as well then.

**Comment by justinjjvanderhooft** [comment]
Marked it for Monday in my calendar @mwang87

**Comment by justinjjvanderhooft** [comment]
https://www.dropbox.com/s/frpzkl5b6p0itc3/MS2LDA_GNPS.pptx?dl=0

**Comment by justinjjvanderhooft** [comment]
apologies for the delay @mwang87! Please find the slides in the link above. I used other modules as example to create a similar style.

**Comment by mwang87** [comment]
Added. Closing
