### ISSUE TITLE
GNPS ReDu Tutorial Slides

### ISSUE THREAD

**Issue by amcaraballor** [CCMS-UCSD/GNPS_TrainingTutorialModules#8]
Hi @mwang87, here we can find the slides for ReDu tutorial that we currently do not have [Link to Dropbox as it is bigger than 10MB]: [GNPS_ReDu](https://www.dropbox.com/s/diz71q90xbyt88z/GNPS_ReDU.pptx?dl=0)

**Comment by mwang87** [comment]
Added Closing
