### ISSUE TITLE
GNPS NAP Tutorial Slides - Done

### ISSUE THREAD

**Issue by amcaraballor** [CCMS-UCSD/GNPS_TrainingTutorialModules#9]
Hi @mwang87, here two more tutorial slides for NAP: 
[NAP_Hands-on](https://www.dropbox.com/s/7g312iz5bhg4fsa/NAP_Hands-on.pptx?dl=0)
[NAP_Theory](https://www.dropbox.com/s/gi0bw7fg2mztwcs/NAP_Theory.pptm?dl=0)
Thanks to Kenny for helping with the NAP_Theory

**Comment by mwang87** [comment]
Merged
